@extends('users.layouts.app')
@section('content')
@include('users.layouts.header')
@include('users.layouts.personal-area')
@include('users.layouts.about-section')
@include('users.layouts.services-section')
@include('users.layouts.portfolio-section')
@include('users.layouts.count-down-section')
@include('users.layouts.timeline-section')
@include('users.layouts.pricing-section')
@include('users.layouts.testimonials-section')
@include('users.layouts.blog')
@include('users.layouts.call-action')
@include('users.layouts.contact-section')
@include('users.layouts.client-section')
{{--  @include('users.layouts.footer-top')  --}}
@endsection
